# Docker 网络内 RocketMQ Broker
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
brokerIP1 = rocketmq-broker
listenPort = 10911
namesrvAddr = rocketmq-namesrv:9876
autoCreateTopicEnable = true
